apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos
  labels:
    {{- include "train-ticket.labels" . | nindent 4 }}
data:
  NACOS_ADDRS: "nacos-0.nacos-headless.{{ .Release.Namespace }}.svc.{{ .Values.nacos.domainName }}:{{ .Values.nacos.serverPort }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq
  labels:
    {{- include "train-ticket.labels" . | nindent 4 }}
data:
  rabbitmq_host: {{ .Values.global.rabbitmq.host | quote }}
  SPRING_RABBITMQ_HOST: {{ .Values.global.rabbitmq.host | quote }}
  SPRING_RABBITMQ_PORT: {{ .Values.global.rabbitmq.port | quote }}
  SPRING_RABBITMQ_USERNAME: {{ .Values.global.rabbitmq.username | quote }}
  SPRING_RABBITMQ_PASSWORD: {{ .Values.global.rabbitmq.password | quote }}
  SPRING_RABBITMQ_VIRTUAL_HOST: {{ .Values.global.rabbitmq.vhost | quote }}
