{{- range $name, $service := .Values.services }}
{{- if $service.dbPrefix }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-mysql
  labels:
    {{- include "train-ticket.labels" $ | nindent 4 }}
type: Opaque
stringData:
  {{ $service.dbPrefix }}MYSQL_HOST: {{ $.Values.global.mysql.host | quote }}
  {{ $service.dbPrefix }}MYSQL_PORT: {{ $.Values.global.mysql.port | quote }}
  {{ $service.dbPrefix }}MYSQL_USER: {{ $.Values.global.mysql.username | quote }}
  {{ $service.dbPrefix }}MYSQL_PASSWORD: {{ $.Values.global.mysql.password | quote }}
  {{ $service.dbPrefix }}MYSQL_DATABASE: {{ $name | replace "-" "_" | quote }}
---
{{- end }}
{{- end }}
